name: Daily CSV Update

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5min
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download vervangingen.csv from OneDrive
        run: |
          curl -L -o vervangingen.csv "https://sgsintpauluseu-my.sharepoint.com/:x:/g/personal/tom_vanwehaege_sgsintpaulus_eu/IQD7rXk8hOHEQZKesI6JldJyAdNbEEiY42W-zOOph353_EA?e=XaNqCf&download=1"

          # Check if file is empty
          if [ ! -s vervangingen.csv ]; then
            echo "Downloaded file is empty."
            exit 1
          fi

          # Check if file contains HTML (SharePoint error page)
          if grep -q "<html" vervangingen.csv; then
            echo "Downloaded file is HTML, not CSV. Likely a redirect or auth issue."
            exit 1
          fi

      - name: Check for Differences
        run: |
          if [ ! -f xibo-vervangingen.csv ]; then
            echo "No existing CSV to compare. Proceeding with update."
            echo "DIFFERENT_CSV=true" >> $GITHUB_ENV
          elif ! diff -q vervangingen.csv xibo-vervangingen.csv > /dev/null; then
            echo "CSV files are different."
            echo "DIFFERENT_CSV=true" >> $GITHUB_ENV
          else
            echo "CSV files are the same. Skipping commit."
            echo "DIFFERENT_CSV=false" >> $GITHUB_ENV
          fi

      - name: Overwrite CSV
        if: env.DIFFERENT_CSV == 'true'
        run: |
          mv vervangingen.csv xibo-vervangingen.csv

      - name: Commit and Push Changes
        if: env.DIFFERENT_CSV == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          timestamp=$(date +'%Y%m%d%H%M%S')
          branch_name="update-csv-$timestamp"

          git checkout -b "$branch_name"
          git add xibo-vervangingen.csv
          git commit -m "Update CSV file"
          git push origin "$branch_name"

          git checkout main
          git merge --no-ff "$branch_name" -m "Merge CSV update $timestamp"
          git push origin main

          git branch -d "$branch_name"
          git push origin --delete "$branch_name"
