name: Daily CSV Update

on:
  schedule:
    - cron: '*/5 * * * *' # elke 5 minuten
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download New CSV
        run: |
          curl -L -o vervangingen.csv "https://sgsintpauluseu-my.sharepoint.com/:x:/g/personal/tom_vanwehaege_sgsintpaulus_eu/IQD7rXk8hOHEQZKesI6JldJyAdNbEEiY42W-zOOph353_EA?e=XaNqCf&download=1"

      - name: Check CSV File Size
        run: |
          if [ -s vervangingen.csv ]; then
            echo "✅ CSV is not empty."
          else
            echo "❌ CSV file is empty."
            exit 1
          fi

      - name: Check for Differences
        run: |
          if [ ! -f xibo-vervangingen.csv ]; then
            echo "No existing CSV found. Assuming difference."
            echo "DIFFERENT_CSV=true" >> $GITHUB_ENV
          elif ! diff -q vervangingen.csv xibo-vervangingen.csv; then
            echo "CSV files are different."
            echo "DIFFERENT_CSV=true" >> $GITHUB_ENV
          else
            echo "CSV files are the same. Skipping commit."
            echo "DIFFERENT_CSV=false" >> $GITHUB_ENV
          fi

      - name: Overwrite CSV
        if: env.DIFFERENT_CSV == 'true'
        run: |
          mv vervangingen.csv xibo-vervangingen.csv

      - name: Commit and Push Changes
        if: env.DIFFERENT_CSV == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add xibo-vervangingen.csv
          git commit -m "Automatische update vanuit OneDrive"
          git push
